apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool
  namespace: metallb-system
spec:
  addresses:
  - ###.###.##.###-###.###.##.###  # Change this to the range of IP addresses you want to use
  autoAssign: true
