apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
data:
  nextcloud-username: YWRtaW4=
  nextcloud-password: YWRtaW4xMjM=  # Base64 encoded "admin123"
  postgresql-password: cGFzc3dvcmQxMjM=  # Base64 encoded "password123"
